# Generated by Django 6.0.7 on 2026-07-19 05:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('is_important', models.BooleanField(default=False)),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-posted_on'],
            },
        ),
        migrations.CreateModel(
            name='AptitudeTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('QUANT', 'Quantitative Aptitude'), ('VERBAL', 'Verbal Ability'), ('LOGICAL', 'Logical Reasoning'), ('CODING', 'Programming Basics')], max_length=20)),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], default='MEDIUM', max_length=10)),
                ('total_questions', models.PositiveIntegerField(default=20)),
                ('duration_minutes', models.PositiveIntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('industry', models.CharField(choices=[('IT', 'IT Services'), ('PRODUCT', 'Product Based'), ('FINANCE', 'Finance'), ('CONSULTING', 'Consulting'), ('CORE', 'Core Engineering'), ('OTHER', 'Other')], default='IT', max_length=20)),
                ('location', models.CharField(default='India', max_length=150)),
                ('website', models.URLField(blank=True)),
                ('founded_year', models.PositiveIntegerField(blank=True, null=True)),
                ('employee_count', models.CharField(blank=True, help_text='e.g. 1,81,000+', max_length=50)),
                ('about', models.TextField(blank=True)),
                ('rating', models.DecimalField(decimal_places=1, default=4.0, max_digits=2)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['-is_featured', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('sent_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-sent_on'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True)),
                ('location', models.CharField(max_length=150)),
                ('job_type', models.CharField(choices=[('FULL_TIME', 'Full Time'), ('PART_TIME', 'Part Time'), ('INTERNSHIP', 'Internship'), ('CONTRACT', 'Contract')], default='FULL_TIME', max_length=20)),
                ('experience', models.CharField(help_text='e.g. 2-4 Yrs', max_length=50)),
                ('salary_min', models.PositiveIntegerField(help_text='LPA, e.g. 6')),
                ('salary_max', models.PositiveIntegerField(help_text='LPA, e.g. 12')),
                ('skills', models.CharField(help_text='Comma separated, e.g. Python, Django, SQL', max_length=300)),
                ('eligibility', models.CharField(default='B.Tech / B.E graduates, 60% and above', max_length=300)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='portal.company')),
            ],
            options={
                'ordering': ['-posted_on'],
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('college', models.CharField(blank=True, max_length=200)),
                ('course', models.CharField(blank=True, max_length=100)),
                ('graduation_year', models.PositiveIntegerField(blank=True, null=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/profile/')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('cover_letter', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('APPLIED', 'Applied'), ('SHORTLISTED', 'Shortlisted'), ('INTERVIEW', 'Interview Scheduled'), ('SELECTED', 'Selected'), ('REJECTED', 'Rejected')], default='APPLIED', max_length=20)),
                ('applied_on', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='portal.job')),
            ],
            options={
                'ordering': ['-applied_on'],
                'unique_together': {('applicant', 'job')},
            },
        ),
    ]
